POM: Remove obsolete junit+mockito workarounds
Extending pom-scijava 44.0.0 means that mockito is already managed at
5.20.0. And the hamcrest-core exclusion no longer seems to be necessary.

And with the hamcrest-core exclusion gone, we can unpin junit as well,
since the following exception is then no longer an issue:

    There was an error in the forked process
    org/hamcrest/SelfDescribing
    java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        ...
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.junit.runner.Computer.getSuite(Computer.java:28)
        at org.junit.runner.Request.classes(Request.java:77)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:111)
        ...
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
    Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 20 more